In [1]:
import json
import numpy as np
import pandas as pd
#yelpdata = pd.read_json('/Users/tiffa/Desktop/review.json',lines=True)
#yelpdata.info()

# read the data from disk and split into lines
# we use .strip() to remove the final (empty) line

business_data = []
with open('/Users/tiffa/Desktop/review.json',encoding="utf8") as f:
    for line in f:
        business_data.append(json.loads(line))
business_df = pd.DataFrame.from_dict(business_data)
business_df.head()


business_id  cool                 date  funny  \
0  ujmEBvifdJM6h6RLv4wQIg     0  2013-05-07 04:34:36      1   
1  NZnhc2sEQy3RmzKTZnqtwQ     0  2017-01-14 21:30:33      0   
2  WTqjgwHlXbSFevF32_DJVw     0  2016-11-09 20:09:03      0   
3  ikCg8xy5JIg_NGPx-MSIDA     0  2018-01-09 20:56:38      0   
4  b1b1eb3uo-w561D0ZfCEiQ     0  2018-01-30 23:07:38      0   

                review_id  stars  \
0  Q1sbwvVQXV2734tPgoKj4Q    1.0   
1  GJXCdrto3ASJOqKeVWPi6Q    5.0   
2  2TzJjDVDEuAW6MR5Vuc1ug    5.0   
3  yi0R0Ugj_xUx_Nek0-_Qig    5.0   
4  11a8sVPMUFtaC7_ABRkmtw    1.0   

                                                text  useful  \
0  Total bill for this horrible service? Over $8G...       6   
1  I *adore* Travis at the Hard Rock's new Kelly ...       0   
2  I have to say that this office really has it t...       3   
3  Went in for a lunch. Steak sandwich was delici...       0   
4  Today was my second out of three sessions I ha...       7   

                  user_id  
0  hG7b0MtEbXx5QzbzE6C_VA  
1  yXQM5uF2jS6es16SJzNHfg  
2  n6-Gk65cPZL6Uz8qRm3NYw  
3  dacAIZ6fTM6mqwW5uxkskg  
4  ssoyf2_x0EQMed6fgHeMyQ

In [2]:
business_df = business_df.drop(columns=['business_id','cool','date','funny','useful','user_id'])

In [3]:
business_df = business_df[business_df.stars != 2.0]
business_df = business_df[business_df.stars != 4.0]

In [4]:
business_df.head()

review_id  stars  \
0  Q1sbwvVQXV2734tPgoKj4Q    1.0   
1  GJXCdrto3ASJOqKeVWPi6Q    5.0   
2  2TzJjDVDEuAW6MR5Vuc1ug    5.0   
3  yi0R0Ugj_xUx_Nek0-_Qig    5.0   
4  11a8sVPMUFtaC7_ABRkmtw    1.0   

                                                text  
0  Total bill for this horrible service? Over $8G...  
1  I *adore* Travis at the Hard Rock's new Kelly ...  
2  I have to say that this office really has it t...  
3  Went in for a lunch. Steak sandwich was delici...  
4  Today was my second out of three sessions I ha...

In [5]:
business_df = business_df[0:5000]

In [6]:
business_df

review_id  stars  \
0     Q1sbwvVQXV2734tPgoKj4Q    1.0   
1     GJXCdrto3ASJOqKeVWPi6Q    5.0   
2     2TzJjDVDEuAW6MR5Vuc1ug    5.0   
3     yi0R0Ugj_xUx_Nek0-_Qig    5.0   
4     11a8sVPMUFtaC7_ABRkmtw    1.0   
6     G7XHMxG0bx9oBJNECG4IFg    3.0   
7     8e9HxxLjjqc9ez5ezzN7iQ    1.0   
9     RS_GTIT6836bCaPy637kNQ    3.0   
11    -I5umRTkhw15RqpKMl_o1Q    1.0   
14    JVcjMhlavKKn3UIt9p9OXA    1.0   
15    svK3nBU7Rk8VfGorlrN52A    5.0   
17    6BnQwlxRn7ZuWdzninM9sQ    3.0   
18    rEITo90tpyKmEfNDp3Ou3A    5.0   
19    4bUyL7lzoWzDZaJETAKREg    3.0   
20    Amo5gZBvCuPc_tZNpHwtsA    5.0   
21    IPw8yWiyqnfBzzWmypUHgg    5.0   
23    S337tATeouQJdoPYyir29w    5.0   
24    D_UvaenM25iNd6aehTZ0MA    5.0   
25    I9HBDyzCqLhTYHCAZIFZQQ    5.0   
26    W1wbNaUnbMy4b9QqY3_SAg    1.0   
27    qm97yMwREr7BKkexlwLFbg    5.0   
28    1daGBpea0sleayFeeXuoYw    1.0   
29    DAC4zWY2ZMa1vxpN9RrDvA    1.0   
30    0AsmPiAQduxh5jE_si8cLA    5.0   
31    bjD0Dqn3k-fi00BXatrytg    1.0   
32    CelUWzp-GnJIiiV1mDUb-g    1.0   
33    hUUfzKeDLo930LA9-v2tWQ    5.0   
34    E6B-2U2sGG3xgmnNWZAEew    1.0   
36    RLbWoIri29BcQ8yjzsvQLQ    5.0   
38    vBRxlgkpDTXjWiYBp1V6GA    1.0   
...                      ...    ...   
7040  8X_Ia8oiVpZ2a1ukm1g-3g    1.0   
7042  X0iYGODyqNS98b0cmI39aQ    5.0   
7043  _6ynS6rreN1yUxwajKKZeg    1.0   
7044  n8fn3q3U0aUf7YtSnl0YTA    5.0   
7045  6s6yn3SqqwUxHMEJM603hg    3.0   
7046  D56xr4xgaPhjYKKVbAhw4g    5.0   
7048  BYpN6yFczwHaZ0aMTSsHKQ    5.0   
7050  HlBy97xCymHUlVN6HgTnxw    1.0   
7051  496K3VKzbwrVoRfdMeJMmw    1.0   
7052  vU6dwBdzuQqmW4XryQ6SCw    3.0   
7053  UF1v9KRsnzBYhIiEwLmM8w    5.0   
7055  4LKgA11t9CwtJINcpU_TGA    3.0   
7056  jZAGKw6NWKEWbbiMpcRuew    3.0   
7059  uSEHFz5ZF9IP_BFxeVK_Dg    5.0   
7061  lgAzJfQHQYayWY9sUmC5DQ    5.0   
7062  DYxx9PByiABTUnwzLexQEg    5.0   
7063  az5OL9HR2QTZCpzT90uZMA    5.0   
7064  fRgcPn1LBysI7OVTyh668w    3.0   
7066  jQ3WS1ZqQVQmD06SYh7PFA    5.0   
7069  -TS8Fh4y-9xaq5OIG2I-og    5.0   
7070  y11itP1bR1vOPQO_AWtDdg    1.0   
7071  a2zv5pd8MZyD66oWFAkyGg    5.0   
7072  7PluGOvGEACJSCQchNLBOA    5.0   
7074  Gv0BDAUvv4QJGqnwF7dOYw    5.0   
7075  A_7VyMTnhnGp9V4kSLwNQA    5.0   
7076  wvf8JHUx8PTGLOKf9JGn_g    3.0   
7077  g8-ETe_2tWHeXXHj_F_r-g    5.0   
7079  ZOGXeTsdfXLmj5bGZT-5sw    5.0   
7080  PUCw8SYsXG4ns7bwt1bVxQ    1.0   
7081  WiABp5TLB9KUwJ-tkOPaPQ    5.0   

                                                   text  
0     Total bill for this horrible service? Over $8G...  
1     I *adore* Travis at the Hard Rock's new Kelly ...  
2     I have to say that this office really has it t...  
3     Went in for a lunch. Steak sandwich was delici...  
4     Today was my second out of three sessions I ha...  
6     Tracy dessert had a big name in Hong Kong and ...  
7     This place has gone down hill.  Clearly they h...  
9     It's a giant Best Buy with 66 registers.  I do...  
11    Walked in around 4 on a Friday afternoon, we s...  
14    I cannot believe how things have changed in 3 ...  
15    You can't really find anything wrong with this...  
17    I love chinese food and I love mexican food. W...  
18    We've been a huge Slim's fan since they opened...  
19    Good selection of classes of beers and mains. ...  
20    Our family LOVES the food here. Quick, friendl...  
21    If you are looking for the best pierogies in P...  
23    Pick any meat on the planet and the chef will ...  
24    Great food, great service. Obviously fried chi...  
25    PlumbSmart provided superior service from begi...  
26    Unfortunately, I must recommend not to conduct...  
27    their pettuccine was fresh-made in the morning...  
28    if i can give this place no stars i would, i o...  
29    This review is in regards to our experience wa...  
30    ended up here because Raku was closed and it r...  
31    I tried this place because my girls are away f...  
32    Love this place downtown but the Scottsdale lo...  
33    Best chinese resto. Highly r

In [7]:
X = business_df['text']
y = business_df['stars']

In [8]:
import string
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer


def text_process(text):
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    
    return [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

bow_transformer = CountVectorizer(analyzer=text_process).fit(X)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\tiffa\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


In [9]:
X = bow_transformer.transform(X)
print('Shape of Sparse Matrix: ', X.shape)
print('Amount of Non-Zero occurrences: ', X.nnz)

Shape of Sparse Matrix:  (5000, 24982)
Amount of Non-Zero occurrences:  227784


In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [11]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [12]:
preds = nb.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, preds))
print('\n')
print(classification_report(y_test, preds))

[[255  26  34]
 [ 23  71 129]
 [ 35  32 895]]


             precision    recall  f1-score   support

        1.0       0.81      0.81      0.81       315
        3.0       0.55      0.32      0.40       223
        5.0       0.85      0.93      0.89       962

avg / total       0.80      0.81      0.80      1500

